baseURL: https://scalpstation.github.io/
theme: hugo-book
defaultContentLanguage: en
languages:
    en:
        title: ScalpStation
        weight: 1
        contentDir: content/en
        languageName: English
    ru:
        title: ScalpStation
        weight: 2
        contentDir: content/ru
        languageName: Russian
enableGitInfo: true

params:
    geekdocLogo: logo.svg
    geekdocRepo: "https://github.com/scalpstation/scalpstation.github.io"
    geekdocEditPath: "tree/main"